Android 2
Renzo1234567/done-android pull request #2
Opened 2017-11-30 19:14 UTC by Renzo1234567

Hacer peticion POST para validar datos de log in

2017-12-03 02:49 UTC, cbarroetam commented on app/src/main/java/com/example/corpsarens2/proyecto3/MainActivity.java
> +                        Toast.makeText(getApplicationContext(),"Algo fallo... " , Toast.LENGTH_LONG).show();
@Renzo1234567 considera registrar en el Log, la causa del error. ASi podras diagnosticar que ocurrio con mas certeza

2017-12-03 02:49 UTC, cbarroetam commented on app/src/main/java/com/example/corpsarens2/proyecto3/MainActivity.java
> +                Toast.makeText(getApplicationContext(),"Algo fallo...",Toast.LENGTH_SHORT).show();
Igual aca, considera generar la entrada en el log

2017-12-03 02:52 UTC, cbarroetam commented on app/src/main/java/com/example/corpsarens2/proyecto3/MainActivity.java
> +        Retrofit retrofit = builder.build();
Este bloque de codigo: https://github.com/Renzo1234567/done-android/blob/1dad05ed2ad311efb604dc330da4c9819affe0a8/app/src/main/java/com/example/corpsarens2/proyecto3/MainActivity.java#L67-L76

se va a repetir por todo el proyecto a medida que comiences a incorporar servicios a la aplicacion. Considera el uso de una clase que aplique el concepto de Fabrica para que no se repita a lo largo del proyecto.

2017-12-03 02:53 UTC, cbarroetam requested changes
Refactorizar la configuracion de Retrofit para simplificar y centralizar, por medio de un Factory, la obtencion de la instancia cliente.

2017-12-03 18:55 UTC, Renzo1234567 commented on app/src/main/java/com/example/corpsarens2/proyecto3/MainActivity.java
> +                        Toast.makeText(getApplicationContext(),"Algo fallo... " , Toast.LENGTH_LONG).show();
Hola profesor, aca no implemente los logs ya que la clase HttpLoggingInterceptor que implemente junto a Retrofit permite capturar en el Logcat de Android Studio todos los errores que pueda ocasionar el servidor , permitiendome asi diagnosticar alguna falla de parte mia al subir el JSON al servidor o de parte del servidor proporcionandome respuestas por parte del servidor por ejemplo la respuesta "400 Bad Request"

2017-12-03 18:56 UTC, Renzo1234567 commented on app/src/main/java/com/example/corpsarens2/proyecto3/MainActivity.java
> +                Toast.makeText(getApplicationContext(),"Algo fallo...",Toast.LENGTH_SHORT).show();
Aca tambien

2017-12-04 08:39 UTC, cbarroetam approved these changes

2017-12-04 08:39 UTC, merged